config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index', as: 'home'
  get '/notes' => 'notes#index'
  post '/create_note' => 'notes#create'
  get 'search', to: 'searches#search'
  # Showing user login, logging them in, logging them out
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  patch '/password' => 'password#update'
  get '/password' => 'password#edit'
  get '/note_roadblocks/:id' => 'solutions#show'

  resources :notes do
    resources :comments
  end

  resources :note_roadblocks do
    resources :solutions
  end

  resources :teams
  resources :password
  resources :admin do
    member do
      patch :set_admin
      delete :remove_admin
    end
  end
  resources :employees
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :note_bodies, dependent: :delete_all
  has_many :note_roadblocks, dependent: :nullify

  accepts_nested_attributes_for :note_bodies, :note_roadblocks

  after_find :ensure_teams_id_has_a_value

  validates :title, presence: true, length: { minimum: 1 }
  validates :teams_id, presence: true

  default_scope { order(created_at: :desc, id: :desc) }

  def team
    Team.find(teams_id)
  end

  def author
    Employee.find(employees_id)
  end

  def bodies
    NoteBody.where(note_id: id)
  end

  def body_for(employee_id)
    NoteBody.find_by(note_id: id, employees_id: employee_id)&.body
  end

  def roadblock_for(employee_id)
    NoteRoadblock.find_by(id: id, employees_id: employee_id)&.body
  end

  def roadblocks
    NoteRoadblock.where(note_id: id)
  end

  private

  def ensure_teams_id_has_a_value
    return unless teams_id.nil?

    self.teams_id = Team::SnapIT.id
    save
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :authorize
  before_action :employee?, only: %i[new create edit destroy update]
  before_action :set_page, only: [:index]

  EMPLOYEE_NOT_PRESENT = 'Employee not present'

  def index
    notes_per_page = 10
    @total_notes = Note.all.length - 1
    @total_pages = (@total_notes.to_i / notes_per_page).ceil
    @notes = Note.limit(notes_per_page).offset(@current_page * notes_per_page)

    redirect_to notes_path if params[:page].to_i > @total_pages || params[:page].to_i.negative?
  end

  def set_page
    @current_page = params[:page].to_i || 0
  end

  def show
    @note = Note.find(params[:id])

    roadblocks = @note.roadblocks
    bodies = @note.bodies
    all_employees = roadblocks.map(&:employees_id) | bodies.map(&:employees_id)
    employees = Employee.find(all_employees.compact)

    @note_content = []
    employees&.each do |e|
      @note_content << {
        name: "#{e.first_name} #{e.last_name}",
        body: bodies.find_by(employees_id: e.id)&.body,
        roadblock: roadblocks.find_by(employees_id: e.id)&.body,
        roadblock_id: roadblocks.find_by(employees_id: e.id)&.id
      }
    end

    @team = Team.find(@note.teams_id)
    # for comments partial
    @users = User.all
  end

  def new
    @teams = Team.active
    @employees = Employee.active
  end

  def create
    if params[:team].nil?
      redirect_to new_note_url, warning: 'Select at least one team to create a note'
      return
    end

    teams = Team.find(params[:team])

    teams.each do |team|
      note = Note.create(title: team.name, teams_id: team.id, employees_id: current_user.as_employee.id)

      team.members.each do |team_member|
        input = params[:note_details][team_member.id.to_s]

        if input[:absent] == '1'
          input[:body] = EMPLOYEE_NOT_PRESENT
          input[:roadblock] = nil
        end

        NoteBody.create(
          body: input[:body],
          note_id: note.id,
          employees_id: team_member.id
        )

        NoteRoadblock.create(
          body: input[:roadblock],
          note_id: note.id,
          employees_id: team_member.id
        )
      end
    end
    redirect_to home_path, success: 'Note Saved'
  end

  def edit
    @note = Note.find(params[:id])
    @employees = Employee.all
    @note_bodies = NoteBody.where(note_id: params[:id])
    @note_roadblocks = NoteRoadblock.all.where(note_id: params[:id])
    @absent_employees = @note_bodies.where(body: EMPLOYEE_NOT_PRESENT).pluck(:employees_id)
  end

  def update
    note = Note.find(params[:id])
    note.update(title: params[:note_edit][:title])

    Employee.all.each do |e|
      input = params[:note_edit][e.id.to_s]
      next unless input.present?

      if input[:absent] == '1'
        NoteBody.find_by(note_id: params[:id], employees_id: e.id).update(body: EMPLOYEE_NOT_PRESENT)
        NoteRoadblock.find_by(note_id: params[:id], employees_id: e.id).update(body: nil)
      else
        NoteBody.find_by(note_id: params[:id], employees_id: e.id).update(body: input[:body])
        NoteRoadblock.find_by(note_id: params[:id], employees_id: e.id).update(body: input[:roadblock])
      end
    end
    redirect_to note, success: 'Update successful'
  end

  def destroy
    redirect_to notes_path, success: 'Note deleted'
  end
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/views/notes/edit.html.erb
<h1> Edit Note </h1>

<%= form_for :note_edit, url: note_path(@note), method: :patch do |note| %>
  <h5><%= @note.title %></h5>
  <% @employees.each do |employee| %>
	<% note_body = @note_bodies.find_by(employees_id: employee.id) %>
	<% next if @note_bodies.find_by(employees_id: employee.id).nil? %>
	<% note_roadblocks = @note_roadblocks.find_by(employees_id: employee.id)%>

    <%= note.fields_for "#{employee.id}" do |f| %>
      <div id="accordion">
        <div class="card">
        <div class="card-wrapper">
          <div class="card-header" id="heading<%="#{employee.id}"%>">
            <h5 class="mb-0">
              <button  type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse<%="#{employee.id}"%>" aria-expanded="false" aria-controls="collapse<%="#{employee.id}"%>">
              <h4><%= employee.last_name %>, <%= employee.first_name %></h4>
              </button>
              <span><%= f.check_box :absent, :checked => @absent_employees.include?(employee.id) %> Employee is not present</span>
            </h5>
          </div>
        </div>

          <div id="collapse<%="#{employee.id}"%>" class="collapse" aria-labelledby="heading<%="#{employee.id}"%>" data-parent="#accordion">
            <div class="card-body">
              <%= f.hidden_field :employee_id, value: employee.id %>

              <p><%= f.text_area :body, :class => 'form-control note-input', value: note_body.body %></p>

              <p><%= f.text_area :roadblock, :class => 'form-control note-input', value: note_roadblocks.body %></p>
              <hr>
    <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  <hr>
  <%= note.submit 'Save Note', ({:class => 'btn btn-primary'}) %>
  <%= link_to "Cancel", note_path(@note), :class => "btn btn-danger"%>
<% end %>

app/views/notes/index.html.erb
<h2>NOTES</h2>


<div class="container">
	<div class="row col-md-12 col-md-offset-2">
    <table class="table table-striped">
			<thead>
				<tr>
					<th>Pod</th>
					<th>Author</th>
					<th>Timestamp</th>
					<th class="text-center" style="width:300px;">Action</th>
				</tr>
			</thead>
			<% @notes.each do |note| %>
				<tr class="custab">
					<td><%= note.team.name %></td>
					<td>
						<% if note.employees_id.nil? %>
							-
						<% else %>
							<%= note.author.first_name %> <%= note.author.last_name %>
						<% end %>
					</td>
					<td><%=note.created_at.in_time_zone('America/Chicago').strftime('%a %D %I:%M %p')%></td>
					<td class="text-center">
						<%= link_to "View", note_path(note.id), class: 'btn btn-info btn-xs' %>
						<% if current_user.as_employee.present? %>
							<%= link_to "Edit", edit_note_path(note.id), class: 'btn btn-warning btn-xs' %>
							<%= link_to "Delete", note_path(note.id), method: :delete, class: 'btn btn-danger btn-xs',
														data: {confirm: 'Are you sure you want to permanently delete this note?'} %>
						<% end %>
					</td>
				</tr>
			<%end%>
    </table>
	</div>
</div>

<div>
	<div style="width:fit-content;margin:0 auto;">
	<% if @current_page.positive? %>
		<%= link_to "Previous", notes_path(page: @current_page - 1), :class => 'btn btn-dark' %>
	<% end %>
	<% unless @current_page == @total_pages %>
		<%= link_to "Next", notes_path(page: @current_page + 1),  :class => 'btn btn-dark'%>
	<% end %>
	</div>
</div>

app/views/notes/new.html.erb
<h1> Create Note </h1>
  <h6><i>Select Pod(s)</i></h6>

<span></span>
<%= form_for :note_details, url: '/create_note', method: :post do |note| %>

  <% @teams.each do |team| %>
    <%= check_box_tag "team[]", team.id, false, class: "teams", data: {team: team.members.pluck(:id)} %>
    <strong><%= team.name %></strong>
  <% end %>

  <% @employees.each do |employee| %>
    <%= note.fields_for "#{employee.id}" do |f| %>
    <div id ="<%="#{employee.id}"%>" class = "employee">
      <div id="accordion">
        <div class="card card-wrapper">
          <div class="card-header" id="heading<%="#{employee.id}"%>">
            <h5 class="mb-0">
              <span><button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse<%="#{employee.id}"%>" aria-expanded="false" aria-controls="collapse<%="#{employee.id}"%>">
              <h4><%= employee.last_name %>, <%= employee.first_name %></h4>
              </button></span>
              <span><%= f.check_box :absent, checked: false %> Employee is not present</span>
            </h5>
          </div>
        </div>

        <div id="collapse<%="#{employee.id}"%>" class="collapse" aria-labelledby="heading<%="#{employee.id}"%>" data-parent="#accordion">
          <div class="card-body">
            <%= f.hidden_field :employee_id, value: employee.id %>
            <h5><%= f.label :body, 'Notes'%></h5>
            <p><%= f.text_area :body, class: 'form-control note-input', placeholder: 'Note' %></p>
            <h5><%= f.label :roadblock, 'Road Blocks'%></h5>
            <p><%= f.text_area :roadblock, class: 'form-control note-input', placeholder: 'Road Blocks'%></p>
    <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <hr>
  <%= note.submit 'Save Note', ({class: 'btn btn-success'}) %>
  <%= link_to "Cancel", home_path, :class => "btn btn-danger"%>
<% end %>

app/views/notes/show.html.erb
<h1> <%= @note.title %></h1>

<h6 class = "text-muted"><i><%= "#{@note.created_at.in_time_zone('America/Chicago').strftime("%A %B %d, %Y")}" %></i></h6>
<% if @note.employees_id.present?%>
  <h6 class = "text-muted"><i> Created by <%= "#{@note.author.first_name} #{@note.author.last_name}" %></i></h6>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Employee</th>
      <th>Note</th>
      <th>Roadblocks</th>
      <th class="text-center" style="width:120px;">Action</th>
    </tr>
  </thead>
  <% @note_content.each do |employee_content| %>
    <tr class="custab">
      <td class="long-text"><%= employee_content[:name] %></td>
      <td><%= employee_content[:body] %></td>
      <td><%= employee_content[:roadblock] %></td>
      <td class="text-center">
        <% unless employee_content[:roadblock].blank? %>
          <%= link_to "Solutions", note_roadblock_path(employee_content[:roadblock_id]), class: 'btn btn-info btn-xs' %>
        <% end %>
      </td>
    </tr>
  <%end%>
</table>

<hr>
<%= render 'comments/comments'%>

<% if @current_user.as_employee.present? %>
  <%=  link_to "Edit Note", edit_note_path(@note), :class => 'btn btn-primary' %>
  <%=  link_to  "Delete Note", note_path(@note), method: :delete, data: {confirm: 'Are you sure'}, :class => 'btn btn-danger'   %>
<% end %>