config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index', as: 'home'
  get '/notes' => 'notes#index'
  post '/create_note' => 'notes#create'
  get 'search', to: 'searches#search'
  # Showing user login, logging them in, logging them out
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  patch '/password' => 'password#update'
  get '/password' => 'password#edit'
  get '/note_roadblocks/:id' => 'solutions#show'

  resources :notes do
    resources :comments
  end

  resources :note_roadblocks do
    resources :solutions
  end

  resources :teams
  resources :password
  resources :admin do
    member do
      patch :set_admin
      delete :remove_admin
    end
  end
  resources :employees
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :note
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  has_many :notes
  default_scope { order(:last_name, :first_name) }
  has_and_belongs_to_many :team

  def self.active
    Employee.where.not(users_id: nil).to_a
  end

  def teams
    team_ids = EmployeesTeam.where(employees_id: id, active: true).map(&:teams_id).uniq
    Team.find(team_ids)
  end

  def roadblock_for(note_id)
    NoteRoadblock.where(employees_id: id, note_id: note_id)
  end

  def first_name=(val)
    write_attribute(:first_name, val.strip.capitalize)
  end

  def last_name=(val)
    write_attribute(:last_name, val.strip.capitalize)
  end

  def email_address=(val)
    write_attribute(:email_address, val.strip.downcase)
  end

  def as_user
    User.find_by(id: users_id)
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/employees_team.rb
# frozen_string_literal: true

class EmployeesTeam < ApplicationRecord
  def self.records_for(team_id)
    EmployeesTeam.where(teams_id: team_id, active: true)
  end
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :note_bodies, dependent: :delete_all
  has_many :note_roadblocks, dependent: :nullify

  accepts_nested_attributes_for :note_bodies, :note_roadblocks

  after_find :ensure_teams_id_has_a_value

  validates :title, presence: true, length: { minimum: 1 }
  validates :teams_id, presence: true

  default_scope { order(created_at: :desc, id: :desc) }

  def team
    Team.find(teams_id)
  end

  def author
    Employee.find(employees_id)
  end

  def bodies
    NoteBody.where(note_id: id)
  end

  def body_for(employee_id)
    NoteBody.find_by(note_id: id, employees_id: employee_id)&.body
  end

  def roadblock_for(employee_id)
    NoteRoadblock.find_by(id: id, employees_id: employee_id)&.body
  end

  def roadblocks
    NoteRoadblock.where(note_id: id)
  end

  private

  def ensure_teams_id_has_a_value
    return unless teams_id.nil?

    self.teams_id = Team::SnapIT.id
    save
  end
end

app/models/note_body.rb
# frozen_string_literal: true

class NoteBody < ApplicationRecord
  belongs_to :note

  def employee
    Employee.find(employees_id)
  end
end

app/models/note_roadblock.rb
# frozen_string_literal: true

class NoteRoadblock < ApplicationRecord
  has_many :solutions, dependent: :delete_all
  belongs_to :note
end

app/models/solution.rb
# frozen_string_literal: true

class Solution < ApplicationRecord
  default_scope { order(created_at: :desc, id: :desc) }
  belongs_to :note_roadblock
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  default_scope { order(:name) }

  SnapIT = Team.find_by(name: 'SnapIT')

  def self.active
    Team.where(active: true)
  end

  def members
    active_employee_ids = EmployeesTeam.where(teams_id: id, active: true).map(&:employees_id)
    Employee.find(active_employee_ids)
  end

  def lead
    Employee.find(lead_id) unless lead_id.nil?
  end

  def self.leads
    Employee.find(Team.active.map(&:lead_id)).to_a.uniq
  end

  def add_member(member_id)
    member_id = member_id.to_i
    return self if members.map(&:id).include?(member_id)

    EmployeesTeam.create(employees_id: member_id, teams_id: id, active: true)
    self
  end

  def remove_member(member_id)
    member_id = member_id.to_i
    return self unless members.map(&:id).include?(member_id)

    EmployeesTeam.find_by(employees_id: member_id, teams_id: id, active: true).update(active: false)
    self
  end

  after_initialize do
    self.active ||= true if new_record?
  end
  has_many :employees_teams, dependent: :delete_all
  has_and_belongs_to_many :employees
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password validations: false

  # Return all user id's of users set as admins
  def self.admin_users
    UserRole.where(role: 'admin').pluck(:users_id)
  end

  def roles
    UserRole.where(users_id: id).map(&:role)
  end

  def admin?
    roles.any?('admin')
  end

  # Return employee id that belongs to the users_id passed
  def as_employee
    Employee.find_by_users_id(id)
  end

  # Return
  def user_name=(val)
    write_attribute(:user_name, val.strip.downcase)
  end
end

app/models/user_role.rb
# frozen_string_literal: true

class UserRole < ApplicationRecord
  enum role: %i[employee admin]

  after_initialize do
    self.role ||= :employee if new_record?
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/edit.html.erb
<br>
<h2><%= @employee.first_name %> <%= @employee.last_name%></h2>

<%= form_for :employee_update, url: admin_path(@employee), method: :patch do |f| %>
	<br>

	<p>
		First Name: 
    <%= f.text_field :first_name, value: @employee.first_name, required: true %>
	</p>

	<p>
		Last Name: 
    <%= f.text_field :last_name, value: @employee.last_name, required: true %>
	</p>

	<br>

	<p>
		Email: 
    <%= f.text_field :email_address, value: @employee.email_address, required: true %>
	</p>

	<br>

	<% if @employee.as_user.admin? %>
		<%= link_to "Remove Admin", remove_admin_admin_path(@employee.id), method: :delete, :class => 'btn btn-outline-secondary',
				data: {confirm: "Remove #{@employee.first_name} #{@employee.last_name} from admin list?"} %>
	<% else %>
		<%= link_to "Make Admin", set_admin_admin_path(@employee.id), method: :patch, :class => 'btn btn-outline-secondary',
				data: {confirm: "Make #{@employee.first_name} #{@employee.last_name} an admin?"} %>
	<% end %>

	<%= f.submit "Save Employee", ({:class => 'btn btn-success'}) %>
	<%= link_to "Cancel", admin_index_path, :class => "btn btn-danger" %>
<% end %>

app/views/admin/index.html.erb
<%= button_to "Add Employee", new_admin_path, method: :get, class: "btn btn-block btn-success create-note-btn" %>
<br>
<h2>Employees</h2>
<br>

<div class="container">
	<div class="row col-md-12 col-md-offset-2">
    <table class="table table-striped">
			<thead>
				<tr>
					<th style="width:10%;">Admin</th>
					<th>Name</th>
					<th>Email</th>
					<th class="text-center" style="width:300px;">Action</th>
				</tr>
			</thead>
			<% @employees.each do |employee| %>
				<tr class="custab">
					<td>
						<% if employee.as_user.admin? %>
							<h5 class = "text-muted"><i>✓</i></h5>
						<% end %>
					</td>
					<td><%="#{employee}"%></td>
					<td><%= employee.email_address %></td>
					<td class="text-center">
						<%= link_to "History", employee_path(employee.id), class: 'btn btn-info btn-xs' %>
						<%= link_to "Edit", edit_admin_path(employee.id), class: 'btn btn-warning btn-xs' %>
						<%= link_to "Delete", employee_path(employee), method: :delete, class: 'btn btn-danger btn-xs',
													data: {confirm: 'Are you sure you want to eliminate this employee?'} %>
					</td>
				</tr>
			<%end%>
    </table>
	</div>
</div>

app/views/admin/new.html.erb
<h2>Add New Employee</h2>
<br>
<%= form_for :employee, local:true, url: admin_index_path, method: :post  do |f| %>
	<p>
		<%= f.text_field :first_name, placeholder: 'First Name', required: true%>
	</p>

	<p>
		<%= f.text_field :last_name, placeholder: 'Last Name', required: true %>
	</p>

	<p>
		<%= f.text_field :email_address, placeholder: 'Email', required: true %>
	</p>

	<hr>

	<h6>Add to Pod</h6>
	<p>
		<% @teams.each do |team| %>
			<%= check_box_tag "team[]", team.id, false, class: "input-check-box" %>
			<%= "#{team.name}" %>
		<% end %>
	</p>

	<hr>

	<%= f.submit ({:class => 'btn btn-primary'}) %>
	<%= link_to "Cancel", admin_index_path, :class => "btn btn-danger" %>
<% end %>

app/views/admin/show.html.erb
<br>
<%= button_to "Back to Employees", admin_index_path, method: :get, class: "btn btn-block btn-dark" %>
<br>
<h1> Employee Page<h1><%= link_to "Edit Employee Details", edit_admin_path(@employee), :class => 'btn btn-warning' %>
<hr>
<h5> Employee Name </h5>
<p> <%= @employee.first_name %> <%= @employee.last_name %></p>

<h4> Employee Email </h4>
<p> <%= @employee.email_address %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stand-Up Notes</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
  </head>
  <body>
    <%# Display company logo and app info %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= image_tag("snap_it_logo.png", :class => 'snap_logo', :alt => "snapIT logo") %>
      <span class="navbar-brand">Stand-Up Notes</span>

      <%# This part of the nav bar is only visible when logged in %>
      <% if current_user %>

        <%# Page Links %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if current_page?(home_path) %>"><%= link_to "Home", home_path, class: "nav-link" %></li>
          <li class="nav-item <%= 'active' if current_page?(notes_path) %>"><%= link_to "Notes", notes_path, class: "nav-link" %></li>
          <li class="nav-item <%= 'active' if current_page?(teams_path) %>"><%= link_to "Pods", teams_path, class: "nav-link" %></li>
          <%# These buttons are only if user has role admin %>
          <% if current_user.admin? %>
            <li class="nav-item <%= 'active' if current_page?(admin_index_path) %>"><%= link_to "Employees", admin_index_path, class: "nav-link" %></li>
          <% end %>
        </ul>

          <%# Display Current User Info %>
          <span class="navbar-text"><small><i style="color:white;">
            Admin
          </i></small></span>

          <%# Dropdown %>
          <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Settings
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <% if current_user.as_employee.present? %>
                <%= link_to "My History", employee_path(1), class: "dropdown-item" %>
              <% end %>
              <%= link_to "Change Password", '/password', class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log Out", '/logout', class: "dropdown-item" %>
            </div>
          </li>
          </ul>
      <% end %>
    </nav>

    <%# When flash messages appear, this is the container for it %>
    <div id="flash_msg">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= name %>'role='alert'> 
          <%= msg %>
        </div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <br>
  </body>
  <footer>
    <br>
  </footer>
</html>